# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wenting Zhao
email: wzhao@cs.cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  Home of Wenting Zhao.
baseurl: "" # the subpath of your site, e.g. /blog
url: "wenting-zhao.github.io" # the base hostname & protocol for your site
twitter_username: wzhao_nlp
github_username:  wenting-zhao

# Build settings
markdown: kramdown
highlighter: rouge
